spring:
  application:
    name: BOOKING-SERVICE
  datasource:
    username: postgres
    password: azizbek2003
    url: jdbc:postgresql://db-azizbek-aws.cj9xb1mfxuhe.ap-northeast-1.rds.amazonaws.com
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect:

host: ${HOST:http://localhost}
services:
 room-url: ${ROOM_URL:http://room-service/room/api/v1/}





eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true

